# Generated by Django 5.2.5 on 2026-05-02 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre_empresa', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'El nombre de la empresa debe tener al menos 2 caracteres.')], verbose_name='Nombre Empresa')),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contacto')),
                ('email', models.EmailField(max_length=191, unique=True, verbose_name='email address')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('rubro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
    ]
