# Generated by Django 5.2.5 on 2026-05-02 19:23

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_codigo_producto_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.IntegerField(blank=True, null=True, validators=[catalogo.models.no_negativo]),
        ),
    ]
